### PR TITLE
Send service file to email

### PR DESCRIPTION
**Pull request by b-dur**
Extended the CreateServiceFile to accept email address via query param, so instead of downloading the file the file will be sent as an email with an attachment.

### CODE REVIEW

**Comment by tgc-dk** [comment]
Are you sure you want to hardcode the from email address...?

**Comment by b-dur** [comment]
Good catch. It definitely shouldn't be mine. Any good way how this maybe could be configurable?

**Comment by tgc-dk** [comment]
Currently db.php is where various configuration is placed, so I'd put it there.

**Comment by b-dur** [comment]
@tgc-dk Passing the Webmaster email address as from email

**Pull request merged**
